name: Publish JAR to GitHub Release

on:
  release:
    types: [published]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Rename JAR
      run: |
        VERSION=${GITHUB_REF#refs/tags/v}
        mv target/*.jar target/owlapi-wrapper-$VERSION.jar

    - name: Upload JAR to GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: target/owlapi-wrapper-*.jar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
